// Emits the versioned catalog for consumers outside this repo: a JSON document
// for tooling and a Dart fixture the Flutter app's test pins itself against.
// The Angular TypeScript file stays the single master; this only reads it.
//
//   npm run export-catalog        write the fixtures
//   npm run check:catalog         verify them without writing anything
//
// The Dart file is a FIXTURE, not an implementation: the mobile app keeps its
// own catalog, and its test asserts the two agree. A mismatch there means the
// phone would price or offer something the server does not.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'contracts', 'catalog');

const { CATALOG_VERSION, MODEL_FAMILIES, EDIT_TOOLS, CREDIT_PACKS, PLAN_CREDITS, STUDIO_MARGIN } =
  await import(join(root, 'src/app/core/catalog/model-families.ts'));

const catalog = {
  catalogVersion: CATALOG_VERSION,
  studioMargin: STUDIO_MARGIN,
  planCredits: PLAN_CREDITS,
  packs: CREDIT_PACKS,
  editTools: EDIT_TOOLS.map((t) => ({ id: t.id, name: t.name, credits: t.creditCost })),
  families: MODEL_FAMILIES.map((f) => ({
    id: f.id,
    name: f.name,
    kind: f.kind,
    provider: f.provider,
    capabilities: {
      versions: f.capabilities.versions?.map((v) => v.value) ?? null,
      resolutions: f.capabilities.resolutions?.map((r) => r.value) ?? null,
      qualities: f.capabilities.qualities?.map((q) => q.value) ?? null,
      aspectRatios: f.capabilities.aspectRatios,
      durations: f.capabilities.durations ?? null,
      modes: f.capabilities.modes ?? null,
      audio: f.capabilities.audio ?? null,
      // Tiers the provider cannot deliver at a given ratio. The phone has to
      // know, or it offers a size the server will refuse.
      resolutionExclusions: f.capabilities.resolutionExclusions ?? null,
      imageInput: f.capabilities.imageInput,
      maskInput: f.capabilities.maskInput,
    },
  })),
};

const json = `${JSON.stringify(catalog, null, 2)}\n`;

const dart = `// GENERATED by scripts/export-catalog.mjs in the vansen web repo.
// Do not edit. Regenerate and copy in whenever CATALOG_VERSION changes.
// ignore_for_file: prefer_single_quotes

const String kCatalogVersion = ${JSON.stringify(CATALOG_VERSION)};

const Map<String, dynamic> kCatalogFixture = ${JSON.stringify(catalog, null, 2)};
`;

function assertFileMatches(path, content) {
  if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
    throw new Error(`catalog drift: ${path}`);
  }
}

const outputs = { 'catalog.json': json, 'model_catalog_fixture.dart': dart };
const checking = process.argv.includes('--check');
for (const [name, content] of Object.entries(outputs)) {
  const path = join(out, name);
  if (checking) {
    assertFileMatches(path, content);
    continue;
  }
  mkdirSync(out, { recursive: true });
  writeFileSync(path, content);
}
console.log(`catalog ${CATALOG_VERSION} ${checking ? 'verified' : 'written'}`);
